#pragma config(Sensor, S4,     Ultrasound,     sensorSONAR)
#pragma config(Motor,  motorA,          Cannon,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftTread,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTread,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Drive Module.c"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		Driver();

		if(joy1Btn(7))
		{
			motor [motorA] = 100;
		}
		else
		{
			motor [motorA] = 0;
		}
	}
}
